### PR TITLE
test architecture supports testrunner container

### LINKED ISSUE #597: Run-to-run changes in the test-runner is causing build failures and test-skips-and-fails
At least two significant errors in the last weeks runs of automated tests would not have occurred if our test-runner were a container based on an invariant image.

The solution is to snapshot our test infrastructure setup login in a docker image, and then use that image in our test-build-system.

This image should derive "FROM CURRENT_JENKINS_RUNNER_IMAGE".

I'll first create an image for the mitaka branch, and then _if necessary_ create other images for other branches (and projects).

Associated Tests:
[""]

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux @szakeri 
Issues:
Fixes #597

Problem: Our test infrastructure was/is plagued with a large number of sources
of change, many of which are outside of our control.
Among these sources of variation:

* the transitive closure of Python packages our tests depend on (frequently
referenced via requirements.txt files)
* the set of packages built in to the BDO provided test runner
* the root Docker image the test runner was built on
* the community constraints files specified in the neutron-lbaas fork we use to
attempt to match the communities state

There are other known sources of uncontrolled variation, the above is the list
of sources of change that are eliminated by the change to containerized testing
this commit is a part of.

Analysis: In order to stablize our test infrastructure the following
enhancements are implemented:

(1) The test runner build specification is now managed by the F5 OpenStack
Integration Team (us) at:  https://gitlab.pdbld.f5net.com/openstack/labbench

(2) Dependencies are incorporated into the testrunner via Dockerfiles.

(3) Where possible git clone is used to record the source code of dependencies
in the relevant layer of the Dockerfile.  The corresponding application is
installed from source in the same layer.

(4) Management of the testrunner, and other microservices, is implemented with
a simple make-based build system.

These enhancements eliminate the above listed sources of variance.  More work
remains with respect to other sources of variance.

Tests: all the tests in "run_neutron_lbaas" were run to confirm the
functionality of this change.

### CODE REVIEW

File: systest/Dockerfile [hunk 1]
```diff
@@ -1,11 +0,0 @@
...
-USER    root
-RUN     apt-get update && \
-        apt-get install -y docker.io=1.12.6-0ubuntu1~16.04.1
-RUN     adduser jenkins staff 
-RUN     git clone https://github.com/pypa/pip.git
-RUN     cd /home/jenkins/pip && \
-        git checkout 022248f6484fe87dc0ef5aec3437f4c7971fd14b && \
-        python ./setup.py install && cd /home/jenkins
-RUN     pip install git+git://github.com/pypa/virtualenv.git@2db288fe1f8b6
-USER    jenkins
```
Comment (zancas) [inline systest/Dockerfile]: This logic has migrated to the `openstack/labbench` repo.

File: systest/Makefile [hunk 2]
```diff
@@ -15,8 +15,6 @@
 
 # Inform make that targets are NOT files.
 .PHONY: all functest \
-install_tlc \
-install_test_infra \
```
Comment (zancas) [inline systest/Makefile]: The logic that used to live in these targets/scripts is now encoded in Dockerfiles in the labbench repo.

File: systest/Makefile [hunk 3]
```diff
@@ -45,16 +43,6 @@ export TEST_DIR := $(abspath $(MAKEFILE_DIR))/../test
...
-# Repos that are used for the tests and environment
-# TLC
-export TLC_DIR := /home/jenkins/tlc
-export TLC_REPO := https://gitlab.pdbld.f5net.com/openstack/tlc.git
-export TLC_BRANCH := buildbot
-
-# toolsbase (replicate internal directory structure for TLC install)
-export TOOLSBASE_DIR := /toolsbase
-export TOOLSBASE_REPO := https://gitlab.pdbld.f5net.com/openstack/tlc-toolsbase.git
-
```
Comment (zancas) [inline systest/Makefile]: This logic was only necessary to support `tlc_install`.

File: systest/Makefile [hunk 4]
```diff
@@ -355,9 +336,8 @@ tempest_12.1.1_undercloud_vlan:
 	export EXCLUDE_FILE=$@.yaml ;\
 	$(MAKE) -C . run_tests
 
-run_tests: install_tlc install_test_infra
-	$(MAKE) -C . setup_tlc_session
+run_tests:
+	$(MAKE) -C . microservice_setup_tlc_session
 	$(MAKE) -C . configure_test_infra
 	$(MAKE) -C . run_neutron_lbaas
-	$(MAKE) -C . run_agent_transfers
```
Comment (zancas) [inline systest/Makefile]: We can refactor these tests, and reactivate them later.

File: systest/scripts/ansible_install_lbaasv2.sh [hunk 5]
```diff
@@ -5,41 +5,46 @@ set -ex
...
     | awk '{print $3}' | xargs`
-SSH_CMD="ssh -i /home/jenkins/.ssh/id_rsa_testlab -o StrictHostKeyChecking=no testlab@${OS_CONTROLLER_IP}"
+SSH_CMD="ssh -i /home/jenkins/.ssh/id_rsa -o StrictHostKeyChecking=no testlab@${OS_CONTROLLER_IP}"
 BIGIP_IP=`${SSH_CMD} "cat /home/testlab/ve_mgmt_ip"`
 BIGIP_IP=${BIGIP_IP%%[[:cntrl:]]}
 NETWORK_TYPES=${TEST_TENANT_NETWORK_TYPE}
 AGENT_LOC=git+https://github.com/F5Networks/f5-openstack-agent.git@${BRANCH}
 DRIVER_LOC=git+https://github.com/F5Networks/f5-openstack-lbaasv2-driver.git@${BRANCH}
-NEUTRON_DRIVER_LOC=https://raw.githubusercontent.com/F5Networks/neutron-lbaas/${RBANCH}/neutron_lbaas/drivers/f5/driver_v2.py
+NEUTRON_DRIVER_LOC=https://raw.githubusercontent.com/F5Networks/neutron-lbaas/stable/${BRANCH}/neutron_lbaas/drivers/f5/driver_v2.py
```
Comment (zancas) [inline systest/scripts/ansible_install_lbaasv2.sh]: oops.

File: systest/scripts/conf/neutron-lbaas.tox.ini [hunk 6]
```diff
@@ -6,13 +6,8 @@ skipsdist = True
 [testenv]
 setenv = VIRTUAL_ENV={envdir}
 usedevelop = True
-install_command =
-  {toxinidir}/tools/tox_install.sh {env:UPPER_CONSTRAINTS_FILE:https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt} {opts} {packages}
```
Comment (zancas) [inline systest/scripts/conf/neutron-lbaas.tox.ini]: Handled in the neutronlbaas layer of the testrunner microservice in the labbench repo.

File: systest/scripts/conf/neutron-lbaas.tox.ini [hunk 7]
```diff
@@ -6,13 +6,8 @@ skipsdist = True
...
 deps =
-  -r{toxinidir}/test-requirements.txt
-  -r{toxinidir}/neutron_lbaas/tests/tempest/requirements.txt
```
Comment (zancas) [inline systest/scripts/conf/neutron-lbaas.tox.ini]: See labbench.

**Comment by zancas** [comment]
OK, folks...   I'd like to run the tests against a session that was set up with `USER=jenkins` which the setup-retry code requires.

Once that's complete, this change will be fully tested.

**Comment by zancas** [comment]
I need to modify `.travis.yaml`.

**Comment by zancas** [comment]
OK, `.travis.yml` changes are non-blocking, but to update travis to use our new testrunner image I believe we need only add `docker run zancas/openstack-testrunner {FOO}` to a couple of lines.

**Comment by zancas** [comment]
OK @pjbreaux I think we should merge this in.   I think now is a great time, because it isolates the change to just this code.

**Comment by zancas** [comment]
@szakeri any chance you could approve this?

File: Jenkinsfile [hunk 8]
```diff
@@ -5,10 +5,11 @@ pipeline {
         docker {
             label "docker"
             registryUrl "https://docker-registry.pdbld.f5net.com"
-            image "bdo/jenkins-worker-ubuntu-16.04:master"
+            image "openstack-infra/drivertestrunner:latest"
             args "-v /etc/localtime:/etc/localtime:ro" \
                 + " -v /srv/mesos/trtl/results:/home/jenkins/results" \
                 + " -v /srv/nfs:/testlab" \
+                + " -v /var/run/docker.sock:/var/run/docker.sock" \
```
Comment (pjbreaux) [inline Jenkinsfile]: Is there any guarantee that this socket will be there in the running Jenkins executor?

File: systest/Makefile (hunk 4 above)
Comment (pjbreaux) [inline systest/Makefile]: We can remove them or exclude them. Either way is fine, since we don't yet know the expectation of these tests.

File: systest/scripts/ansible_install_lbaasv2.sh [hunk 9]
```diff
@@ -5,41 +5,46 @@ set -ex
 OS_CONTROLLER_IP=`/tools/bin/tlc --sid ${TEST_SESSION} symbols \
     | grep openstack_controller1ip_data_direct \
     | awk '{print $3}' | xargs`
-SSH_CMD="ssh -i /home/jenkins/.ssh/id_rsa_testlab -o StrictHostKeyChecking=no testlab@${OS_CONTROLLER_IP}"
+SSH_CMD="ssh -i /home/jenkins/.ssh/id_rsa -o StrictHostKeyChecking=no testlab@${OS_CONTROLLER_IP}"
```
Comment (pjbreaux) [inline systest/scripts/ansible_install_lbaasv2.sh]: Does this key exist in the container on the executor?

File: systest/scripts/microservice_setup_tlc_session.sh [hunk 10]
```diff
@@ -15,12 +15,84 @@
...
 #
 
-set -ex
+set -x
 
-# Run the setup & commands for the session
-/tools/bin/tlc --session ${TEST_SESSION} --config ${TLC_FILE} --debug setup
-/tools/bin/tlc --session ${TEST_SESSION} --debug cmd ready
-/tools/bin/tlc --session ${TEST_SESSION} --debug cmd test_env
+set +e
```
Comment (pjbreaux) [inline systest/scripts/microservice_setup_tlc_session.sh]: This change and some of the following changes should already be in mitaka.

Comment (pjbreaux) [inline systest/scripts/microservice_setup_tlc_session.sh]: Hmm, I guess because it's a new file.

File: tox.ini [hunk 11]
```diff
@@ -6,9 +6,9 @@ passenv = TEMPEST_CONFIG_DIR
 setenv =
   OS_TEST_PATH={toxinidir}/f5lbaasdriver/test/tempest/tests
 deps =
-  -rrequirements.test.txt
+  pytest
 changedir = f5lbaasdriver/test/tempest/tests/
-commands = py.test -vra {posargs}
+commands = py.test {posargs}
```
Comment (pjbreaux) [inline tox.ini]: Will dropping the '-vra' args cause any problems in trtl parsing results, or will we lose verbosity since we're removing -v?

File: Jenkinsfile (hunk 8 above)
Comment (zancas) [inline Jenkinsfile]: It's standard.

File: systest/scripts/ansible_install_lbaasv2.sh (hunk 9 above)
Comment (zancas) [inline systest/scripts/ansible_install_lbaasv2.sh]: Yes.

File: tox.ini (hunk 11 above)
Comment (zancas) [inline tox.ini]: Good catch!  I'll put those back.

Comment (zancas) [inline tox.ini]: I remember this now..
Some flags are in 2 places.   See `scripts/run_neutron_lbaas.sh`
I'm going to push _all_ flags into `systest/scripts/run_neutron_lbaas.sh` for finer grained control.
