### PR TITLE
Fix failed preamble

### LINKED ISSUE #421: tlc test-infrastructure failure issues aren't killing the TEST_SESION.

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux 
    Ensure that a failure in preamble steps kills the

    rest of the test session.

    Issues:
    Fixes #421

    Problem: Steps prior to the test run in the automated test system were
    failing, but the subsequent test run step still attempted to execute
    its doomed task.

    Analysis: This was caused by using Step0 || Cleanup.  The failure
    in Step0 was concealed by the successful Cleanup.

    Tests: NONE

### CODE REVIEW

File: systest/scripts/cleanup_failed_tlc.sh [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+set -x
+
+# We only need to cleanup the session, we didn't use barbican-enabled TLC file
+tlc --session ${TEST_SESSION} --debug cleanup && exit -1
```
Comment (pjbreaux) [inline systest/scripts/cleanup_failed_tlc.sh]: Something seems strange with this:

http://www.tldp.org/LDP/abs/html/exitcodes.html

**Comment by pjbreaux** [comment]
Looks good, pending test with broken TLC session.

**Comment by zancas** [comment]
@pjbreaux I tested the fix in the following way:

I added the below target to the Makefile, then I invoked it with:  `make breaker`

Finally I examined that output and found the custom error code "217".

```
breaker:
    $(MAKE) -C . install_tlc
    $(MAKE) -C . install_test_infra
    $(MAKE) -C . configure_test_infra
```
